@startuml
'https://plantuml.com/class-diagram

package Domain{
    package Entity{
        class Model{}
        class Rule{}
    }
'    package Game{
'        class Game{}
'    }
    class GameManager{}
    interface IPresenter{}
    interface IRepository{}
    class Command{}

}

package Presentation{
    package UI{
        class View{}
    }
    class ViewModel{}
    class Presenter{}
    class Controller{}
}

package Data{
    class Repository{}
}

GameManager --> Entity
GameManager -> IPresenter
GameManager --> IRepository
Command --> GameManager
Controller --> Command
Presenter --|> IPresenter
Repository --|> IRepository
Presenter -> ViewModel
View -> ViewModel
'
'abstract class AbstractList
'abstract AbstractCollection
'interface List
'interface Collection
'
'List <|-- AbstractList
'Collection <|-- AbstractCollection
'
'Collection <|- List
'AbstractCollection <|- AbstractList
'AbstractList <|-- ArrayList
'
'class ArrayList {
'Object[] elementData
'size()
'}
'
'enum TimeUnit {
'DAYS
'HOURS
'MINUTES
'}

@enduml